"""
Chat endpoint for RAG-powered chatbot with memory.
Supports anonymous user identification, multimodal images, and personalized memory.

Calls LangGraphRAGService.achat() — fully async, non-blocking pipeline.
"""
from fastapi import APIRouter, HTTPException, Request, status, Depends
from fastapi.responses import StreamingResponse
from typing import List, Optional

from slowapi import Limiter
from slowapi.util import get_remote_address

from app.schemas.chat import ChatRequest, ChatResponse, ChatMessage, MemoryStats, UserStats
from app.services.langgraph_rag import get_langgraph_service, LangGraphRAGService
from app.core.config import settings

# Re-use the same limiter instance created in main.py (accessed via app.state)
limiter = Limiter(key_func=get_remote_address)

# Memory imports (Pinecone preferred, FAISS fallback)
if settings.PINECONE_API_KEY:
    from app.services.pinecone_memory import get_pinecone_memory_service as get_memory_service
    MEMORY_TYPE = "pinecone"
else:
    from app.services.memory import get_memory_service
    MEMORY_TYPE = "faiss"

router = APIRouter()


def get_rag_service() -> LangGraphRAGService:
    """Dependency to get the LangGraph RAG service"""
    try:
        return get_langgraph_service()
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"RAG service unavailable: {str(e)}"
        )


@router.post("/chat", response_model=ChatResponse)
@limiter.limit("20/minute")   # per IP — prevents any single client from overwhelming the API
async def chat(
    request: Request,
    body: ChatRequest,
    rag: LangGraphRAGService = Depends(get_rag_service),
):
    """
    Chat with the RAG-powered CAFS assistant (supports text + images)
    
    - **question**: Your question about courses, certifications, etc.
    - **user_id**: Anonymous user ID for personalized memory (generated by client)
    - **session_id**: Session ID for grouping conversations
    - **chat_history**: Optional previous messages for context
    - **k**: Number of documents to retrieve (1-20, default: 5)
    - **use_memory**: Search past conversations for context (default: true)
    - **store_in_memory**: Save this conversation to memory (default: true)
    - **image_data**: Base64-encoded image (optional, supports PNG/JPEG/GIF/WebP)
    - **image_mime_type**: MIME type of the image (optional)
    
    Returns answer, sources, and memory usage info.
    """
    try:
        # Convert chat history format if provided
        chat_history = None
        if body.chat_history:
            chat_history = [
                (msg.role, msg.content)
                for msg in body.chat_history
            ]
        
        # ── Call async pipeline (non-blocking — event loop stays free) ────────
        result = await rag.achat(
            question=body.question,
            chat_history=chat_history,
            k=body.k,
            use_memory=body.use_memory,
            store_in_memory=body.store_in_memory,
            user_id=body.user_id,
            session_id=body.session_id,
            image_data=body.image_data,
            image_mime_type=body.image_mime_type,
        )
        
        return ChatResponse(**result)
        
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Configuration error: {str(e)}"
        )
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Vector store not found: {str(e)}"
        )
    except Exception as e:
        import traceback
        error_detail = str(e)
        print(f"Chat error: {error_detail}")
        print(traceback.format_exc())
        
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing chat request: {error_detail}"
        )


@router.post("/stream")
@limiter.limit("20/minute")
async def chat_stream(
    request: Request,
    body: ChatRequest,
    rag: LangGraphRAGService = Depends(get_rag_service),
):
    """
    Streaming chat endpoint — returns tokens as Server-Sent Events (SSE).

    The response is a stream of lines in this format:
      data: {"type": "token",  "content": "Hello"}
      data: {"type": "done",   "sources": [...], "memory_used": true}
      data: [DONE]

    Use this endpoint instead of /chat for the best user experience —
    words appear immediately instead of waiting for the full response.
    """
    try:
        chat_history = None
        if body.chat_history:
            chat_history = [(msg.role, msg.content) for msg in body.chat_history]

        return StreamingResponse(
            rag.astream_chat(
                question=body.question,
                chat_history=chat_history,
                k=body.k,
                use_memory=body.use_memory,
                store_in_memory=body.store_in_memory,
                user_id=body.user_id,
                session_id=body.session_id,
                image_data=body.image_data,
                image_mime_type=body.image_mime_type,
            ),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                # Tell Nginx NOT to buffer this response — send bytes immediately
                "X-Accel-Buffering": "no",
            },
        )
    except Exception as e:
        import traceback
        print(f"Stream endpoint error: {e}")
        print(traceback.format_exc())
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error starting stream: {str(e)}",
        )


@router.get("/health")
async def health_check(rag: LangGraphRAGService = Depends(get_rag_service)):
    """Check if RAG service is healthy"""
    memory_stats = {}
    try:
        memory = get_memory_service()
        memory_stats = memory.get_stats()
    except:
        memory_stats = {"total_conversations": 0, "index_size": 0}
    
    return {
        "status": "healthy",
        "vector_store_loaded": rag.vector_store is not None,
        "llm_initialized": rag.llm is not None,
        "vision_llm_initialized": rag.vision_llm is not None,
        "memory_initialized": rag.memory is not None,
        "memory_type": MEMORY_TYPE,
        "documents_count": len(rag.vector_store.index_to_docstore_id) if rag.vector_store else 0,
        "memory_stats": memory_stats,
    }


@router.get("/memory/stats", response_model=MemoryStats)
async def get_memory_stats():
    """Get memory statistics"""
    try:
        memory = get_memory_service()
        stats = memory.get_stats()
        return MemoryStats(**stats)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting memory stats: {str(e)}"
        )


@router.delete("/memory/clear")
async def clear_memory():
    """Clear all memory (past conversations)"""
    try:
        if MEMORY_TYPE == "pinecone":
            memory = get_memory_service()
            success = memory.clear_all_memory()
            if not success:
                raise Exception("Failed to clear Pinecone memory")
        else:
            import os
            import shutil
            
            memory_path = "memory_index"
            user_memory_path = "user_memories"
            
            if os.path.exists(memory_path):
                shutil.rmtree(memory_path)
            if os.path.exists(user_memory_path):
                shutil.rmtree(user_memory_path)
            
            from app.services import memory
            memory._memory_service = None
        
        return {"status": "success", "message": f"Memory cleared successfully ({MEMORY_TYPE})"}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error clearing memory: {str(e)}"
        )


@router.get("/user/{user_id}/stats", response_model=UserStats)
async def get_user_stats(user_id: str):
    """Get statistics for a specific anonymous user"""
    try:
        memory = get_memory_service()
        stats = memory.get_user_stats(user_id)
        return UserStats(**stats)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting user stats: {str(e)}"
        )


@router.get("/user/{user_id}/history")
async def get_user_history(user_id: str, limit: int = 20):
    """Get conversation history for a specific anonymous user"""
    try:
        memory = get_memory_service()
        history = memory.get_user_history(user_id, limit=limit)
        return {"user_id": user_id, "conversations": history, "count": len(history)}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting user history: {str(e)}"
        )


@router.get("/user/{user_id}/session/{session_id}")
async def get_session_history(user_id: str, session_id: str):
    """Get conversation history for a specific session"""
    try:
        memory = get_memory_service()
        history = memory.get_session_history(user_id, session_id)
        return {
            "user_id": user_id, 
            "session_id": session_id, 
            "conversations": history,
            "count": len(history)
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting session history: {str(e)}"
        )


@router.delete("/user/{user_id}/clear")
async def clear_user_memory(user_id: str):
    """Clear all memory for a specific user"""
    try:
        memory = get_memory_service()
        success = memory.clear_user_memory(user_id)
        if success:
            return {"status": "success", "message": f"Memory cleared for user {user_id}"}
        else:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to clear user memory"
            )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error clearing user memory: {str(e)}"
        )
